In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
from scipy.stats import norm, skew 
from scipy.special import boxcox1p

In [2]:
TC = pd.read_csv('./input/Train_call.txt', sep='\t')

In [3]:
TC.describe()

,Chromosome,Start,End,Nclone,Array.129,Array.34,Array.67,Array.24,Array.22,Array.36,...,Array.64,Array.89,Array.30,Array.35,Array.93,Array.10,Array.123,Array.100,Array.134,Array.130
count,2834.000000,2.834000e+03,2.834000e+03,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,...,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000
mean,10.769231,6.335894e+07,6.434233e+07,82.845095,0.009174,-0.034227,-0.199365,-0.208892,-0.015879,-0.141849,...,-0.039167,0.066690,0.348624,0.024700,0.336627,-0.157375,0.011997,0.022230,0.173959,0.049047
std,6.473031,4.985699e+07,5.017314e+07,118.814507,0.758471,0.620192,0.607739,0.752531,0.534145,0.560173,...,0.661762,0.292509,0.539168,0.394218,0.699164,0.677356,0.701366,0.198476,0.820501,0.601264
min,1.000000,7.120000e+02,2.916900e+04,2.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,5.000000,2.695314e+07,2.812676e+07,9.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000,0.000000
50%,11.000000,5.203528e+07,5.280112e+07,38.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,17.000000,8.733472e+07,8.827873e+07,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,23.000000,2.453086e+08,2.454338e+08,1522.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000

In [4]:
TC.head()

,Chromosome,Start,End,Nclone,Array.129,Array.34,Array.67,Array.24,Array.22,Array.36,...,Array.64,Array.89,Array.30,Array.35,Array.93,Array.10,Array.123,Array.100,Array.134,Array.130
0,1,2927,43870,3,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
1,1,85022,216735,4,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
2,1,370546,372295,4,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,-1,0
3,1,471671,786483,5,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,-1,0
4,1,792533,907406,13,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,-1,0

In [18]:
str(TC.Chromosome.values[0]) + '_'

'1_'

In [6]:
TClinical = pd.read_csv('./input/Train_clinical.txt', sep='\t')

In [7]:
TClinical

       Sample    Subgroup
0   Array.129       HER2+
1    Array.34         HR+
2    Array.67         HR+
3    Array.24  Triple Neg
4    Array.22  Triple Neg
5    Array.36         HR+
6    Array.49       HER2+
7    Array.16       HER2+
8   Array.146  Triple Neg
9   Array.143       HER2+
10   Array.65         HR+
11   Array.62  Triple Neg
12    Array.4       HER2+
13   Array.76       HER2+
14  Array.118  Triple Neg
15  Array.154  Triple Neg
16   Array.48         HR+
17    Array.6       HER2+
18   Array.39         HR+
19   Array.86         HR+
20  Array.112  Triple Neg
21   Array.79       HER2+
22  Array.124         HR+
23   Array.19       HER2+
24   Array.27         HR+
25  Array.106       HER2+
26  Array.110       HER2+
27   Array.69  Triple Neg
28   Array.73       HER2+
29   Array.95         HR+
..        ...         ...
70   Array.75       HER2+
71  Array.139       HER2+
72    Array.2         HR+
73  Array.117         HR+
74   Array.60         HR+
75   Array.38  Triple Neg
76   Array.72       HER2+
77  Array.104  Triple Neg
78  Array.137         HR+
79  Array.145  Triple Neg
80   Array.31  Triple Neg
81  Array.135  Triple Neg
82  Array.111  Triple Neg
83    Array.7         HR+
84   Array.21       HER2+
85   Array.53       HER2+
86   Array.59         HR+
87   Array.71  Triple Neg
88   Array.47  Triple Neg
89  Array.107  Triple Neg
90   Array.64  Triple Neg
91   Array.89         HR+
92   Array.30  Triple Neg
93   Array.35         HR+
94   Array.93  Triple Neg
95   Array.10       HER2+
96  Array.123         HR+
97  Array.100         HR+
98  Array.134         HR+
99  Array.130       HER2+

[100 rows x 2 columns]

In [42]:
TCall = TC.T

In [12]:
TCall.index

Index(['Chromosome', 'Start', 'End', 'Nclone', 'Array.129', 'Array.34',
       'Array.67', 'Array.24', 'Array.22', 'Array.36',
       ...
       'Array.64', 'Array.89', 'Array.30', 'Array.35', 'Array.93', 'Array.10',
       'Array.123', 'Array.100', 'Array.134', 'Array.130'],
      dtype='object', length=104)

In [40]:
TC['biomarkers'] = TC['Chromosome'].map(str) + '_' + TC['Start'].map(str) + '_' + TC['End'].map(str)

In [43]:
TCall

,0,1,2,3,4,5,6,7,8,9,...,2824,2825,2826,2827,2828,2829,2830,2831,2832,2833
Chromosome,1,1,1,1,1,1,1,1,1,1,...,23,23,23,23,23,23,23,23,23,23
Start,2927,85022,370546,471671,792533,912799,1271190,1676445,1738295,2481927,...,151067607,152422390,152552851,152576854,152994680,153062077,153466463,153504394,153938998,153997146
End,43870,216735,372295,786483,907406,1266212,1590570,1703748,2477597,2562342,...,152416606,152548587,152570071,152935130,153054487,153452633,153491568,153933426,153989329,154492924
Nclone,3,4,4,5,13,96,45,4,104,14,...,159,20,6,64,5,57,4,55,5,43
Array.129,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,0,1,1,1,1,1
Array.34,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.67,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.24,0,0,0,0,0,0,0,-1,0,0,...,0,0,0,0,0,0,0,0,0,0
Array.22,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.36,0,0,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,1,1,1
Array.49,0,0,0,0,0,0,0,0,0,0,...,2,1,1,1,1,1,1,1,1,1
Array.16,0,0,0,0,-1,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.146,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.143,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.65,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,2,2,2,2
Array.62,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,1
Array.4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,1
Array.76,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.118,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.154,1,1,0,0,0,0,0,0,-1,-1,...,0,0,0,0,0,0,0,0,0,0
Array.48,1,0,0,0,0,0,1,0,0,0,...,1,1,1,1,0,1,1,1,1,1
Array.6,0,0,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,1,1,1
Array.39,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,0,1,1,1,1,1,1,1
Array.86,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.112,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
Array.79,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.124,0,0,0,0,0,0,0,0,2,0,...,2,1,1,1,1,1,1,2,2,2
Array.19,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,2,1,1,1,2,1
Array.27,0,0,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,1,1,1
Array.106,0,0,0,0,0,0,0,0,-1,-1,...,2,2,2,2,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Array.139,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,2,1,1,1,1,1
Array.2,1,1,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.117,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.60,0,0,0,0,0,0,0,-1,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.38,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.72,1,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.104,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.137,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.145,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,0
Array.31,1,1,1,1,1,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2
Array.135,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
Array.111,1,1,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,1,1,1,1
Array.7,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.21,0,0,0,0,0,0,0,-1,0,0,...,2,2,2,2,2,2,2,2,2,2
Array.53,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
Array.59,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,0,0,0,0,0,0,0,0,0,0
Array.71,0,0,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,1,1,1,1
Array.47,0,0,0,0,0,0,0,0,-1,0,...,2,2,1,2,2,2,2,2,2,2
Array.107,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.64,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,2,2,2,2
Array.89,0,0,0,1,1,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.30,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Array.35,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.93,0,0,1,1,1,1,1,1,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.10,0,0,0,0,0,0,0,0,0,0,...,1,1,0,1,1,1,1,1,1,1
Array.123,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.100,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.134,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,1
Array.130,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
biomarkers,1_2927_43870,1_85022_216735,1_370546_372295,1_471671_786483,1_792533_907406,1_912799_1266212,1_1271190_1590570,1_1676445_1703748,1_1738295_2477597,1_2481927_2562342,...,23_151067607_152416606,23_152422390_152548587,23_152552851_152570071,23_152576854_152935130,23_152994680_153054487,23_153062077_153452633,23_153466463_153491568,23_153504394_153933426,23_153938998_153989329,23_153997146_154492924

In [25]:
TC = TC.drop(columns="biomarkers")

In [27]:
# iterate over rows with iterrows()
for index, row in TC.head().iterrows():
     # access data using column names
     print(index, row['Chromosome'], row['Start'], row['End'])

0 1 2927 43870
1 1 85022 216735
2 1 370546 372295
3 1 471671 786483
4 1 792533 907406