In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
from scipy.stats import norm, skew 
from scipy.special import boxcox1p

In [2]:
TC = pd.read_csv('./input/Train_call.txt', sep='\t')

In [3]:
TC.describe()

,Chromosome,Start,End,Nclone,Array.129,Array.34,Array.67,Array.24,Array.22,Array.36,...,Array.64,Array.89,Array.30,Array.35,Array.93,Array.10,Array.123,Array.100,Array.134,Array.130
count,2834.000000,2.834000e+03,2.834000e+03,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,...,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000,2834.000000
mean,10.769231,6.335894e+07,6.434233e+07,82.845095,0.009174,-0.034227,-0.199365,-0.208892,-0.015879,-0.141849,...,-0.039167,0.066690,0.348624,0.024700,0.336627,-0.157375,0.011997,0.022230,0.173959,0.049047
std,6.473031,4.985699e+07,5.017314e+07,118.814507,0.758471,0.620192,0.607739,0.752531,0.534145,0.560173,...,0.661762,0.292509,0.539168,0.394218,0.699164,0.677356,0.701366,0.198476,0.820501,0.601264
min,1.000000,7.120000e+02,2.916900e+04,2.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,5.000000,2.695314e+07,2.812676e+07,9.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000,0.000000
50%,11.000000,5.203528e+07,5.280112e+07,38.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,17.000000,8.733472e+07,8.827873e+07,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,23.000000,2.453086e+08,2.454338e+08,1522.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000

In [4]:
TC.head()

,Chromosome,Start,End,Nclone,Array.129,Array.34,Array.67,Array.24,Array.22,Array.36,...,Array.64,Array.89,Array.30,Array.35,Array.93,Array.10,Array.123,Array.100,Array.134,Array.130
0,1,2927,43870,3,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
1,1,85022,216735,4,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
2,1,370546,372295,4,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,-1,0
3,1,471671,786483,5,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,-1,0
4,1,792533,907406,13,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,-1,0

In [18]:
str(TC.Chromosome.values[0]) + '_'

'1_'

In [6]:
TClinical = pd.read_csv('./input/Train_clinical.txt', sep='\t')

In [7]:
TClinical

       Sample    Subgroup
0   Array.129       HER2+
1    Array.34         HR+
2    Array.67         HR+
3    Array.24  Triple Neg
4    Array.22  Triple Neg
5    Array.36         HR+
6    Array.49       HER2+
7    Array.16       HER2+
8   Array.146  Triple Neg
9   Array.143       HER2+
10   Array.65         HR+
11   Array.62  Triple Neg
12    Array.4       HER2+
13   Array.76       HER2+
14  Array.118  Triple Neg
15  Array.154  Triple Neg
16   Array.48         HR+
17    Array.6       HER2+
18   Array.39         HR+
19   Array.86         HR+
20  Array.112  Triple Neg
21   Array.79       HER2+
22  Array.124         HR+
23   Array.19       HER2+
24   Array.27         HR+
25  Array.106       HER2+
26  Array.110       HER2+
27   Array.69  Triple Neg
28   Array.73       HER2+
29   Array.95         HR+
..        ...         ...
70   Array.75       HER2+
71  Array.139       HER2+
72    Array.2         HR+
73  Array.117         HR+
74   Array.60         HR+
75   Array.38  Triple Neg
76   Array.72       HER2+
77  Array.104  Triple Neg
78  Array.137         HR+
79  Array.145  Triple Neg
80   Array.31  Triple Neg
81  Array.135  Triple Neg
82  Array.111  Triple Neg
83    Array.7         HR+
84   Array.21       HER2+
85   Array.53       HER2+
86   Array.59         HR+
87   Array.71  Triple Neg
88   Array.47  Triple Neg
89  Array.107  Triple Neg
90   Array.64  Triple Neg
91   Array.89         HR+
92   Array.30  Triple Neg
93   Array.35         HR+
94   Array.93  Triple Neg
95   Array.10       HER2+
96  Array.123         HR+
97  Array.100         HR+
98  Array.134         HR+
99  Array.130       HER2+

[100 rows x 2 columns]

In [40]:
TC['biomarkers'] = TC['Chromosome'].map(str) + '_' + TC['Start'].map(str) + '_' + TC['End'].map(str)

In [44]:
TC.head()

,Chromosome,Start,End,Nclone,Array.129,Array.34,Array.67,Array.24,Array.22,Array.36,...,Array.89,Array.30,Array.35,Array.93,Array.10,Array.123,Array.100,Array.134,Array.130,biomarkers
0,1,2927,43870,3,0,0,0,0,0,0,...,0,1,0,0,0,0,0,-1,0,1_2927_43870
1,1,85022,216735,4,0,0,0,0,0,0,...,0,1,0,0,0,0,0,-1,0,1_85022_216735
2,1,370546,372295,4,0,0,0,0,0,0,...,0,1,0,1,0,0,0,-1,0,1_370546_372295
3,1,471671,786483,5,0,0,0,0,0,0,...,1,1,0,1,0,0,0,-1,0,1_471671_786483
4,1,792533,907406,13,0,0,0,0,0,0,...,1,1,0,1,0,0,0,-1,0,1_792533_907406

In [25]:
TC = TC.drop(columns="biomarkers")

In [27]:
# iterate over rows with iterrows()
for index, row in TC.head().iterrows():
     # access data using column names
     print(index, row['Chromosome'], row['Start'], row['End'])

0 1 2927 43870
1 1 85022 216735
2 1 370546 372295
3 1 471671 786483
4 1 792533 907406

In [45]:
tf_TC = TC.drop(columns=["Chromosome", "Start", "End", "Nclone"])

In [47]:
# Get the DataFrame column names as a list
clist = list(tf_TC.columns)

# Rearrange list the way you like 
clist_new = clist[-1:]+clist[:-1]   # brings the last column in the first place

# Pass the new list to the DataFrame - like a key list in a dict 
tf_TC = tf_TC[clist_new]
tf_TC

,biomarkers,Array.129,Array.34,Array.67,Array.24,Array.22,Array.36,Array.49,Array.16,Array.146,...,Array.64,Array.89,Array.30,Array.35,Array.93,Array.10,Array.123,Array.100,Array.134,Array.130
0,1_2927_43870,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
1,1_85022_216735,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
2,1_370546_372295,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,-1,0
3,1_471671_786483,0,0,0,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,-1,0
4,1_792533_907406,0,0,0,0,0,0,0,-1,0,...,0,1,1,0,1,0,0,0,-1,0
5,1_912799_1266212,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,-1,0
6,1_1271190_1590570,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,-1,0
7,1_1676445_1703748,0,0,0,-1,0,0,0,0,0,...,0,0,1,0,1,0,0,0,-1,0
8,1_1738295_2477597,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
9,1_2481927_2562342,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
10,1_2574555_2580342,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
11,1_2611444_2641811,0,0,0,0,1,0,0,0,0,...,1,1,1,0,1,2,1,0,1,0
12,1_2643540_2645074,0,0,0,0,1,0,0,0,0,...,1,1,1,0,1,0,1,0,1,0
13,1_2664285_2665530,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,-1,0
14,1_2672694_2832087,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
15,1_2854198_2856899,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,-1,0
16,1_2870100_2880675,0,0,0,0,1,0,0,0,0,...,1,1,1,0,1,1,0,0,1,1
17,1_2882919_2901629,0,0,0,0,1,0,0,0,0,...,1,1,1,0,1,1,1,0,1,1
18,1_2903052_3112977,0,0,0,0,0,0,0,-1,0,...,0,0,1,0,0,0,0,0,-1,0
19,1_3125822_3135062,2,0,0,0,0,0,0,-1,0,...,0,0,1,0,0,0,2,0,-1,0
20,1_3136815_3137481,2,0,0,0,0,0,0,-1,0,...,0,0,1,0,0,0,2,0,-1,0
21,1_3149648_3157982,0,0,0,0,0,0,-1,-1,0,...,0,0,1,0,0,0,0,0,-1,0
22,1_3166706_3521038,0,0,0,0,0,0,-1,-1,0,...,0,0,1,0,0,0,0,0,-1,0
23,1_3521345_3798798,0,0,0,0,0,0,-1,-1,0,...,0,0,1,0,0,0,0,0,-1,1
24,1_3810936_6606212,0,0,0,0,0,0,-1,-1,0,...,0,0,1,0,0,0,0,0,-1,0
25,1_6613363_8038878,0,0,0,0,0,0,-1,-1,0,...,0,0,1,0,0,0,0,0,-1,0
26,1_8050444_10537398,0,0,0,0,0,0,-1,-1,0,...,0,0,1,0,0,0,0,0,-1,0
27,1_10551320_12533269,0,0,0,0,0,0,-1,-1,0,...,0,0,0,0,0,0,0,0,-1,0
28,1_12544104_12768740,0,0,0,0,0,0,-1,-1,0,...,0,0,0,0,0,0,0,0,-1,0
29,1_12774453_12788158,0,0,0,-1,0,0,-1,-1,0,...,0,0,0,0,0,0,0,0,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2804,23_89922998_90087775,1,1,1,1,1,1,1,0,1,...,1,1,1,1,2,1,0,1,1,1
2805,23_90107813_90588017,1,1,1,1,1,1,1,1,1,...,1,1,1,1,2,1,0,1,1,1
2806,23_90626987_90763396,1,1,1,1,1,1,1,0,1,...,1,1,1,1,2,1,0,1,1,1
2807,23_90837054_90936838,0,0,1,1,1,1,1,0,1,...,1,1,1,1,2,1,0,1,1,1
2808,23_90947440_91203848,1,0,1,1,1,1,1,0,1,...,1,1,1,1,2,1,0,1,1,1
2809,23_91234699_91344716,2,1,1,1,1,1,1,1,1,...,1,2,1,1,2,1,0,1,1,1
2810,23_91365063_91372700,1,0,1,1,1,1,1,0,1,...,1,1,1,1,1,1,0,1,1,1
2811,23_91404795_91459679,1,0,1,0,1,1,1,0,1,...,0,1,1,1,1,1,0,1,1,1
2812,23_91489731_91607636,0,0,1,0,1,1,1,0,1,...,0,1,1,0,1,1,0,1,1,1
2813,23_91632143_92103804,1,0,1,1,1,1,1,0,1,...,0,1,1,1,1,1,0,1,1,1
2814,23_92209094_95651579,2,1,1,1,1,1,2,1,1,...,1,1,1,1,0,1,1,1,1,1
2815,23_95696214_108087627,2,1,1,1,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2816,23_108169857_122414714,2,1,1,2,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2817,23_122417938_131366673,2,1,1,2,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2818,23_131385521_132949963,2,1,1,2,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2819,23_132998038_140285388,2,1,1,0,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2820,23_140416671_144045173,2,1,1,0,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2821,23_144052935_145145074,2,1,1,0,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2822,23_145164724_149589730,2,1,1,0,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2823,23_149594807_151064869,2,1,1,0,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2824,23_151067607_152416606,2,1,1,0,1,1,2,1,1,...,1,1,1,1,1,1,1,1,1,1
2825,23_152422390_152548587,2,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2826,23_152552851_152570071,2,1,1,0,1,0,1,1,1,...,1,1,1,1,1,0,1,1,1,1
2827,23_152576854_152935130,2,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2828,23_152994680_153054487,0,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2829,23_153062077_153452633,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2830,23_153466463_153491568,1,1,1,0,1,1,1,1,1,...,2,1,1,1,1,1,1,1,1,1
2831,23_153504394_153933426,1,1,1,0,1,1,1,1,1,...,2,1,1,1,1,1,1,1,1,1
2832,23_153938998_153989329,1,1,1,0,1,1,1,1,1,...,2,1,1,1,1,1,1,1,1,1
2833,23_153997146_154492924,1,1,1,0,1,1,1,1,1,...,2,1,1,1,1,1,1,1,1,1

In [48]:
TCall = tf_TC.T

In [50]:
TCall.head()

,0,1,2,3,4,5,6,7,8,9,...,2824,2825,2826,2827,2828,2829,2830,2831,2832,2833
biomarkers,1_2927_43870,1_85022_216735,1_370546_372295,1_471671_786483,1_792533_907406,1_912799_1266212,1_1271190_1590570,1_1676445_1703748,1_1738295_2477597,1_2481927_2562342,...,23_151067607_152416606,23_152422390_152548587,23_152552851_152570071,23_152576854_152935130,23_152994680_153054487,23_153062077_153452633,23_153466463_153491568,23_153504394_153933426,23_153938998_153989329,23_153997146_154492924
Array.129,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,0,1,1,1,1,1
Array.34,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.67,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
Array.24,0,0,0,0,0,0,0,-1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [54]:
TCall.to_csv('modified_train_call.csv', index=True)

In [57]:
md_TC = pd.read_csv('modified_train_call.csv')

In [59]:
result = pd.merge(md_TC,
                  TClinical[['Sample', 'Subgroup']],
                  on=['Sample'],
                  how='left')

In [72]:
result['Subgroup'] = result['Subgroup'].map({'HER2+': 0, 'HR+': 1, 'Triple Neg': 2})

In [76]:
result

,1_2927_43870,1_85022_216735,1_370546_372295,1_471671_786483,1_792533_907406,1_912799_1266212,1_1271190_1590570,1_1676445_1703748,1_1738295_2477597,1_2481927_2562342,...,23_152422390_152548587,23_152552851_152570071,23_152576854_152935130,23_152994680_153054487,23_153062077_153452633,23_153466463_153491568,23_153504394_153933426,23_153938998_153989329,23_153997146_154492924,Subgroup
0,0,0,0,0,0,0,0,0,0,0,...,2,2,2,0,1,1,1,1,1,0
1,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
2,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
3,0,0,0,0,0,0,0,-1,0,0,...,0,0,0,0,0,0,0,0,0,2
4,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,2
5,0,0,0,0,0,0,0,0,0,0,...,1,0,1,1,1,1,1,1,1,1
6,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
7,0,0,0,0,-1,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
8,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,2
9,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
10,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,2,2,2,2,1
11,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,2
12,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,0
13,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
14,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,2
15,1,1,0,0,0,0,0,0,-1,-1,...,0,0,0,0,0,0,0,0,0,2
16,1,0,0,0,0,0,1,0,0,0,...,1,1,1,0,1,1,1,1,1,1
17,0,0,0,0,0,0,0,0,0,0,...,1,0,1,1,1,1,1,1,1,0
18,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,0,1,1,1,1,1,1,1,1
19,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
20,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
21,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
22,0,0,0,0,0,0,0,0,2,0,...,1,1,1,1,1,1,2,2,2,1
23,0,0,0,0,0,0,0,0,0,0,...,1,1,1,2,1,1,1,2,1,0
24,0,0,0,0,0,0,0,0,0,0,...,1,0,1,1,1,1,1,1,1,1
25,0,0,0,0,0,0,0,0,-1,-1,...,2,2,2,2,2,2,2,2,1,0
26,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,0
27,1,0,0,0,0,0,0,1,0,0,...,1,1,1,1,1,1,1,1,1,2
28,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
29,1,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
71,0,0,0,0,0,0,0,0,0,0,...,1,1,1,2,1,1,1,1,1,0
72,1,1,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
73,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
74,0,0,0,0,0,0,0,-1,0,0,...,1,1,1,1,1,1,1,1,1,1
75,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,2
76,1,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
77,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,2
78,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
79,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,0,2
80,1,1,1,1,1,1,1,1,1,1,...,2,2,2,2,2,2,2,2,2,2
81,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
82,1,1,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,1,1,1,2
83,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
84,0,0,0,0,0,0,0,-1,0,0,...,2,2,2,2,2,2,2,2,2,0
85,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,0
86,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,0,0,0,0,0,0,0,0,0,1
87,0,0,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,1,1,1,2
88,0,0,0,0,0,0,0,0,-1,0,...,2,1,2,2,2,2,2,2,2,2
89,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,2
90,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,2,2,2,2,2
91,0,0,0,1,1,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
92,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,2
93,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
94,0,0,1,1,1,1,1,1,0,0,...,1,1,1,1,1,1,1,1,1,2
95,0,0,0,0,0,0,0,0,0,0,...,1,0,1,1,1,1,1,1,1,0
96,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
97,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
98,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,1
99,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0

In [83]:
features_list = np.array(result.columns).tolist()

In [84]:
features_list.remove('Subgroup')

In [85]:
features_list

['1_2927_43870',
 '1_85022_216735',
 '1_370546_372295',
 '1_471671_786483',
 '1_792533_907406',
 '1_912799_1266212',
 '1_1271190_1590570',
 '1_1676445_1703748',
 '1_1738295_2477597',
 '1_2481927_2562342',
 '1_2574555_2580342',
 '1_2611444_2641811',
 '1_2643540_2645074',
 '1_2664285_2665530',
 '1_2672694_2832087',
 '1_2854198_2856899',
 '1_2870100_2880675',
 '1_2882919_2901629',
 '1_2903052_3112977',
 '1_3125822_3135062',
 '1_3136815_3137481',
 '1_3149648_3157982',
 '1_3166706_3521038',
 '1_3521345_3798798',
 '1_3810936_6606212',
 '1_6613363_8038878',
 '1_8050444_10537398',
 '1_10551320_12533269',
 '1_12544104_12768740',
 '1_12774453_12788158',
 '1_12800742_12805297',
 '1_12833868_13002452',
 '1_13520352_15852641',
 '1_15858551_16119613',
 '1_16126501_16531740',
 '1_16551324_16592466',
 '1_16672053_16680432',
 '1_16693433_16750002',
 '1_16757397_16794038',
 '1_16799163_16836986',
 '1_16954838_16997273',
 '1_17030134_17037487',
 '1_17042808_19187091',
 '1_19200088_21470929',
 '1_21483025_21545437',
 '1_21558697_22668805',
 '1_22674759_23463832',
 '1_23469376_25318800',
 '1_25354765_25402278',
 '1_25414726_25433465',
 '1_25441018_26227863',
 '1_26233527_26722236',
 '1_26737835_26751009',
 '1_26758077_27414811',
 '1_27418631_27637052',
 '1_27650970_27755668',
 '1_27765928_29080585',
 '1_29088543_30687222',
 '1_30716764_30984527',
 '1_31006782_31124964',
 '1_31136968_31957740',
 '1_31968013_33181040',
 '1_33189868_34166798',
 '1_34172947_35330813',
 '1_35336344_35895515',
 '1_35903416_37578554',
 '1_37599215_38399540',
 '1_38432360_38569674',
 '1_38648737_39428343',
 '1_39437661_40202959',
 '1_40207650_40612758',
 '1_40617288_40677227',
 '1_40682830_41867848',
 '1_41873732_42747586',
 '1_42754729_43839204',
 '1_43848683_44593810',
 '1_44600018_45223413',
 '1_45231107_46047207',
 '1_46054586_46436383',
 '1_46445058_47002412',
 '1_47020328_47076960',
 '1_47089264_48831518',
 '1_48841029_48963712',
 '1_48974558_49671800',
 '1_49686548_50400238',
 '1_50444082_51401581',
 '1_51408483_52434446',
 '1_52445317_53651141',
 '1_53661750_55331098',
 '1_55339131_55523339',
 '1_55559966_56093730',
 '1_56126922_56811818',
 '1_56820392_57352466',
 '1_57359130_58257959',
 '1_58269395_58818282',
 '1_58829706_59938549',
 '1_59947024_60037860',
 '1_60048731_60931948',
 '1_60943372_61455192',
 '1_61460755_62257156',
 '1_62265513_62775298',
 '1_62781892_63279284',
 '1_63297252_63739396',
 '1_63746181_64381618',
 '1_64392452_65044702',
 '1_65061124_65363623',
 '1_65377733_65684038',
 '1_65691013_66605594',
 '1_66624841_66943717',
 '1_66956044_67293111',
 '1_67304899_67564224',
 '1_67574404_69349603',
 '1_69374719_70163952',
 '1_70172264_70544007',
 '1_70553640_70787481',
 '1_70848676_70955685',
 '1_70968966_72065805',
 '1_72080289_72473289',
 '1_72489681_72620747',
 '1_72661597_74078153',
 '1_74137824_74816963',
 '1_74824437_75454027',
 '1_75473473_76096464',
 '1_76105071_76128015',
 '1_76167515_76719796',
 '1_76735134_77210667',
 '1_77217365_77934334',
 '1_77945975_79392599',
 '1_79437815_80901791',
 '1_80938887_81107155',
 '1_81184008_83075209',
 '1_83100179_83359798',
 '1_83381408_83603746',
 '1_83635029_84586214',
 '1_84590209_84901413',
 '1_84921910_86224479',
 '1_86236843_87585025',
 '1_87607672_87697095',
 '1_87749501_87791319',
 '1_87839437_89193171',
 '1_89198467_91213470',
 '1_91230845_91708215',
 '1_91714670_93739491',
 '1_93748351_97087853',
 '1_97110991_102417008',
 '1_102443157_103810269',
 '1_103819551_103875725',
 '1_104018651_104671817',
 '1_104696813_106107236',
 '1_106163050_107403052',
 '1_107408809_108467581',
 '1_108571690_109922013',
 '1_109933787_109968401',
 '1_109987805_110453999',
 '1_110464125_110577138',
 '1_110588200_112717534',
 '1_112725478_113471063',
 '1_113508337_114220736',
 '1_114228794_114235706',
 '1_114245958_114853862',
 '1_114863525_115372000',
 '1_115389481_116062013',
 '1_116081666_116824183',
 '1_116847623_116861515',
 '1_116880909_116906096',
 '1_116925150_116938461',
 '1_116948867_117006671',
 '1_117015146_117751415',
 '1_117757490_118781178',
 '1_118811438_119105315',
 '1_119131184_119266053',
 '1_119271891_119774102',
 '1_119783556_119942294',
 '1_119963572_120232261',
 '1_120313797_120384620',
 '1_120405944_120737345',
 '1_120761983_120923696',
 '1_141474904_141491470',
 '1_141500919_141527782',
 '1_142116690_142435868',
 '1_142444242_142565191',
 '1_142570866_142598507',
 '1_142610589_142871406',
 '1_142877399_143526765',
 '1_143543580_144966156',
 '1_144975464_145023947',
 '1_145647143_145716245',
 '1_145820605_146012014',
 '1_146473741_146512434',
 '1_146525071_146549143',
 '1_146581869_146634734',
 '1_146661770_149362629',
 '1_149369522_149394958',
 '1_149403519_149573806',
 '1_149579637_149582884',
 '1_149591108_149598429',
 '1_149604744_150808620',
 '1_150815602_151998352',
 '1_151998685_152605084',
 '1_152617283_155145482',
 '1_155152973_156497370',
 '1_156504203_156715120',
 '1_156722904_157446463',
 '1_157457777_157769567',
 '1_157779753_158111315',
 '1_158123386_158211115',
 '1_158222895_158292447',
 '1_158296040_158314837',
 '1_158319014_158365270',
 '1_158378189_158382079',
 '1_158392593_158736756',
 '1_158747329_164242059',
 '1_164247118_165948301',
 '1_165958802_165988174',
 '1_166003996_166010822',
 '1_166018172_168812476',
 '1_168818982_172497794',
 '1_172527923_176446701',
 '1_176455950_179420685',
 '1_179443743_179575821',
 '1_179581225_181371569',
 '1_181387023_182641159',
 '1_182657845_186034550',
 '1_186062909_186274119',
 '1_186293872_189329179',
 '1_189337051_193443252',
 '1_193480150_193527058',
 '1_193556792_193630262',
 '1_193652057_199041703',
 '1_199047681_199054142',
 '1_199087690_199111062',
 '1_199135441_199222301',
 '1_199273751_199356111',
 '1_199363774_201157571',
 '1_201169853_202358631',
 '1_202366885_203532522',
 '1_203539204_205954108',
 '1_205966175_208143743',
 '1_208148352_209359643',
 '1_209366118_211118685',
 '1_211126341_211395327',
 '1_211438238_212152890',
 '1_212163869_213601626',
 '1_213607905_215165364',
 '1_215199726_217395427',
 '1_217416088_219300768',
 '1_219311634_221538990',
 '1_221557056_224126341',
 '1_224140920_225920251',
 '1_225926558_231061656',
 '1_231067740_234760702',
 '1_234776770_236274333',
 '1_236280081_237042779',
 '1_237050563_238730140',
 '1_238747201_239156984',
 '1_239190321_239313778',
 '1_239337733_239364269',
 '1_239391358_239517083',
 '1_239544570_239630032',
 '1_239663268_244617610',
 '1_244627520_244676774',
 '1_244693374_244865778',
 '1_244870377_244942436',
 '1_244947984_244955806',
 '1_244961779_244970723',
 '1_245009770_245014643',
 '1_245054641_245071941',
 '1_245082256_245121447',
 '1_245134410_245140268',
 '1_245150122_245299678',
 '1_245308564_245433846',
 '2_712_125634',
 '2_143031_165346',
 '2_167106_176745',
 '2_196212_479448',
 '2_485052_3016048',
 '2_3072994_4495693',
 '2_4600483_5064198',
 '2_5117160_8963807',
 '2_8972669_10440704',
 '2_10446234_11268822',
 '2_11273719_11824126',
 '2_11839789_15741307',
 '2_15752122_20346474',
 '2_20354952_22147571',
 '2_22164275_23148262',
 '2_23178086_23798605',
 '2_23809995_25541135',
 '2_25551899_29745341',
 '2_29758580_34597887',
 '2_34614581_34702220',
 '2_34730412_34868034',
 '2_34904779_39267014',
 '2_39284752_41599090',
 '2_41616449_43362384',
 '2_43367043_44064629',
 '2_44073585_44107287',
 '2_44112923_46581831',
 '2_46600135_47534465',
 '2_47541529_48962866',
 '2_49007696_50317220',
 '2_50329312_56794730',
 '2_56853626_57106587',
 '2_57141220_60843704',
 '2_60860846_61005290',
 '2_61025070_61061211',
 '2_61069435_67262586',
 '2_67280403_69113514',
 '2_69119613_73764874',
 '2_73769146_74670974',
 '2_74676485_81995821',
 '2_82033369_87033744',
 '2_87287735_87839798',
 '2_88099999_89162648',
 '2_89203734_89712785',
 '2_89727641_89953713',
 '2_91057159_91234354',
 '2_91240477_91321476',
 '2_91494116_91569435',
 '2_91683845_94918111',
 '2_94940234_94964565',
 '2_94970664_98466443',
 '2_98472519_101487776',
 '2_101508783_106387775',
 '2_106409285_110341019',
 '2_110563411_111085061',
 '2_111108426_113884106',
 '2_113910766_114036896',
 '2_114146068_115199661',
 '2_115206978_115251658',
 '2_115260305_116378260',
 '2_116395687_120822517',
 '2_120829609_123225447',
 '2_123281054_126438234',
 '2_126478953_126745976',
 '2_126799274_126901119',
 '2_126922829_130410215',
 '2_130427665_130453073',
 '2_130458581_131785093',
 '2_131792734_131931782',
 '2_131945577_132042781',
 '2_132067307_132196569',
 '2_132210961_132323628',
 '2_132327604_132349355',
 '2_132419295_132947789',
 '2_132974227_139709714',
 '2_139773806_147365650',
 '2_147413433_147652606',
 '2_147700457_158902610',
 '2_158911197_159695436',
 '2_159712195_164848314',
 '2_164879282_165653813',
 '2_165662108_171006374',
 '2_171017426_173478545',
 '2_173485322_174896336',
 '2_174901679_180212390',
 '2_180223718_187349250',
 '2_187359105_190451844',
 '2_190458269_190481066',
 '2_190485380_196058781',
 '2_196090504_198648767',
 '2_198658046_216382286',
 '2_216395222_217154796',
 '2_217169713_224771175',
 '2_224833869_229675328',
 '2_229700351_231853847',
 '2_231862922_233057465',
 '2_233066421_235036486',
 '2_235061664_235732587',
 '2_235740357_236665001',
 '2_236672959_242242118',
 '2_242430070_242784096',
 '3_39066_342654',
 '3_348251_478718',
 '3_515536_517145',
 '3_521064_574415',
 '3_586636_625689',
 '3_641257_4099960',
 '3_4109224_4214897',
 '3_4226329_9771752',
 '3_9779380_9918123',
 '3_9923074_11677508',
 '3_11686988_12710784',
 '3_12735694_14873985',
 '3_14887411_16613213',
 '3_16617887_16778176',
 '3_16792439_18668016',
 '3_18712267_19922255',
 '3_19936335_24520200',
 '3_24543616_25463517',
 '3_25470432_29923292',
 '3_29936736_31279861',
 '3_31298148_34796905',
 '3_34840321_39070614',
 '3_39083092_41241584',
 '3_41249898_46752789',
 '3_46761824_46823673',
 '3_46829442_48626775',
 '3_48631976_48677740',
 '3_48686316_50274167',
 '3_50277922_50326943',
 '3_50330225_54374166',
 '3_54381805_55759111',
 '3_55767891_60816395',
 '3_60825422_64093778',
 '3_64100021_65243724',
 '3_65284372_69024511',
 '3_69036237_69714887',
 '3_69736891_71096721',
 '3_71105921_71561684',
 '3_71570203_73535935',
 '3_73545783_75469606',
 '3_75479859_75535753',
 '3_75546791_75799957',
 '3_75845446_75858339',
 '3_75870144_75896020',
 '3_75914406_75957900',
 '3_75971233_76019295',
 '3_76042344_77513375',
 '3_77524016_79388058',
 '3_79401618_80929281',
 '3_80959005_82751614',
 '3_82801964_84189335',
 '3_84212782_84761534',
 '3_84773539_86079447',
 '3_86093476_86238114',
 '3_86304015_87271517',
 '3_87287192_87311658',
 '3_87336579_87661897',
 '3_87696516_88166248',
 '3_88179775_88662813',
 '3_88671596_89473678',
 '3_89488409_89516057',
 '3_89531802_89654152',
 '3_89663968_90219681',
 '3_90236603_90284660',
 '3_90296455_90391698',
 '3_95043863_95338953',
 '3_95346425_97340020',
 '3_97384282_97943959',
 '3_97955574_100144881',
 '3_100159418_103058802',
 '3_103067334_103845179',
 '3_103869497_105247720',
 '3_105296320_106577524',
 '3_106589477_111089189',
 '3_111105693_113356479',
 '3_113370366_113847282',
 '3_113854434_114473399',
 '3_114484581_115444884',
 '3_115450295_119473378',
 '3_119496988_123302196',
 '3_123307820_126884366',
 '3_127015333_127130406',
 '3_127138046_128434521',
 '3_128485208_128664764',
 '3_128683027_130206126',
 '3_130220686_130840184',
 '3_130849527_131199964',
 '3_131215316_131299415',
 '3_131310594_136853762',
 '3_136891846_137841243',
 '3_137852057_143671669',
 '3_143686906_144718154',
 '3_144727213_153247166',
 '3_153300999_156963893',
 '3_156981865_160212878',
 '3_160231691_163957219',
 '3_163966040_163987465',
 '3_163997236_164023510',
 '3_164038925_164101784',
 '3_164112881_164333847',
 '3_164343718_164427869',
 '3_164454066_166625316',
 '3_166639991_168786545',
 '3_168804852_170462923',
 '3_170472437_173237997',
 '3_173247425_173637617',
 '3_173645852_176989598',
 '3_177004388_181135381',
 '3_181148817_181183735',
 '3_181189842_185001990',
 '3_185013005_186735226',
 '3_186745732_193414542',
 '3_193425674_193467200',
 '3_193476462_196656506',
 '3_196908262_196937230',
 '3_196947293_196962380',
 '3_196972157_199325300',
 '3_199333505_199383479',
 '4_5224_61876',
 '4_62447_79281',
 '4_81744_90787',
 '4_96888_175366',
 '4_185368_826605',
 '4_833085_843614',
 '4_846154_890807',
 '4_897264_916652',
 '4_917610_3551253',
 '4_3556852_3568531',
 '4_3573080_3641241',
 '4_3673803_4147283',
 '4_4308119_4314081',
 '4_4327213_4358339',
 '4_4360195_8850748',
 '4_9047040_9477600',
 '4_9490990_15375010',
 '4_15384438_24218777',
 '4_24224491_26261405',
 '4_26278444_30019771',
 '4_30083533_30560722',
 '4_30573671_31049842',
 '4_31107518_36697482',
 '4_36738699_36983238',
 '4_37025175_37407426',
 '4_37413005_41489363',
 '4_41496099_42685919',
 '4_42710489_45504577',
 '4_45535603_45884120',
 '4_45894555_47334481',
 '4_47347301_48644676',
 '4_48659573_48887700',
 '4_48893757_48924159',
 '4_49056466_49422736',
 '4_52530029_52542008',
 '4_52552859_52866092',
 '4_52891744_53940563',
 '4_53947082_54222055',
 '4_54233704_54818502',
 '4_54830408_56191506',
 '4_56204828_56528111',
 '4_56538786_56886195',
 '4_56900758_57769341',
 '4_57777789_59357407',
 '4_59395290_60641180',
 '4_60678904_61229724',
 '4_61252645_62435526',
 '4_62446231_63222419',
 '4_63275984_64652340',
 '4_64680305_65414644',
 '4_65481054_65744197',
 '4_65794186_66816761',
 '4_66835016_67211677',
 '4_67234063_67381734',
 '4_67404716_67833957',
 '4_67867679_69042487',
 '4_69215734_69311985',
 '4_69789443_70305861',
 '4_70334625_70410860',
 '4_70442343_70445716',
 '4_70473911_70726327',
 '4_70749905_71906729',
 '4_71911043_72985198',
 '4_72994111_74368203',
 '4_74379535_74719357',
 '4_74730754_75668590',
 '4_75673613_76622083',
 '4_76653831_77049387',
 '4_77061006_77300382',
 '4_77303574_77856862',
 '4_77863667_78685195',
 '4_78691810_79606045',
 '4_79616351_80607032',
 '4_80615625_81139934',
 '4_81162799_82540203',
 '4_82569422_84308939',
 '4_84316855_87125034',
 '4_87135123_88309706',
 '4_88320867_88381178',
 '4_88392625_89297860',
 '4_89306720_89782811',
 '4_89790637_91468725',
 '4_91479631_92419006',
 '4_92426426_93211181',
 '4_93240865_100160841',
 '4_100169541_102644734',
 '4_102672728_104401802',
 '4_104413477_106965473',
 '4_106972190_110834066',
 '4_110841462_119681984',
 '4_119714411_119812578',
 '4_119819380_119910398',
 '4_119958548_120638168',
 '4_120650347_124374816',
 '4_124390047_126128011',
 '4_126172292_132931013',
 '4_132983429_133222805',
 '4_133264013_133574024',
 '4_133582875_133743518',
 '4_133758444_135910286',
 '4_135920331_141938438',
 '4_141948988_142632507',
 '4_142656232_143241597',
 '4_143274574_145390888',
 '4_145396784_148091215',
 '4_148098972_152558944',
 '4_152569997_157221896',
 '4_157228097_162174965',
 '4_162205286_162321148',
 '4_162347852_163724527',
 '4_163764301_166540017',
 '4_166559793_171072076',
 '4_171088261_178331211',
 '4_178373531_178507603',
 '4_178531509_182779062',
 '4_182828885_186804557',
 '4_186810460_186843576',
 '4_186862697_186942944',
 '4_186950719_188875290',
 '4_188886189_190844427',
 '4_190887518_191025356',
 '4_191037678_191046020',
 '4_191062719_191134340',
 '4_191144773_191165971',
 '4_191191940_191311992',
 '5_75149_90692',
 '5_103093_277082',
 '5_285775_706486',
 '5_714149_719885',
 '5_725942_745859',
 '5_763494_786455',
 '5_802518_826044',
 '5_837253_859176',
 '5_873416_878290',
 '5_916822_999736',
 '5_1007442_2438174',
 '5_2448553_4633545',
 '5_4645911_6343008',
 '5_6356267_9839414',
 '5_9867745_12822565',
 '5_12835355_15170666',
 '5_15204662_17067228',
 '5_17100908_17382633',
 '5_17406393_17549618',
 '5_17570523_17719479',
 '5_17739874_17979702',
 '5_18001755_18894305',
 '5_18945305_20776045',
 '5_20792335_21966989',
 '5_21979223_22038375',
 '5_22056803_26293381',
 '5_26323047_30449516',
 '5_30493484_32133136',
 '5_32146491_32203336',
 '5_32209048_34105512',
 '5_34119335_34407822',
 '5_34446079_35291657',
 '5_35313005_36062965',
 '5_36075592_36816672',
 '5_36845462_39113391',
 '5_39121212_41235739',
 '5_41241052_41596520',
 '5_41620761_43330593',
 '5_43332656_44495322',
 '5_44516010_44864831',
 '5_44870238_45938397',
 '5_49619946_49866980',
 '5_49892983_49980085',
 '5_49988952_50268244',
 '5_50324634_51282261',
 '5_51321507_51678728',
 '5_51720583_51852968',
 '5_51881238_54336548',
 '5_54350373_55141379',
 '5_55148225_57204282',
 '5_57220729_57800810',
 '5_57805582_58473974',
 '5_58484078_60277014',
 '5_60285997_62401952',
 '5_62457701_65999278',
 '5_66011537_68773114',
 '5_68785515_68850823',
 '5_69274433_70345552',
 '5_70422297_70698794',
 '5_70716278_70721505',
 '5_70752359_71062539',
 '5_71077546_89933522',
 '5_89942176_93303306',
 '5_93308740_93320336',
 '5_93328253_96508341',
 '5_96522323_96603723',
 '5_96637773_98418818',
 '5_98471909_100277629',
 '5_100290917_104805236',
 '5_104851801_108410768',
 '5_108424581_119080004',
 '5_119108165_125801997',
 '5_125809649_131839536',
 '5_131845023_140196482',
 '5_140203440_140221835',
 '5_140228321_140427074',
 '5_140433878_142819410',
 '5_142831583_149027600',
 '5_149050787_150137980',
 '5_150148732_150201145',
 '5_150224239_152555267',
 '5_152572508_153979903',
 '5_154006451_157875296',
 '5_157900279_159729154',
 '5_159735059_161722215',
 '5_161749783_162958203',
 '5_162999771_166652000',
 '5_166676986_169967887',
 '5_169983718_171644531',
 '5_171653443_173359849',
 '5_173368856_173702519',
 '5_173739318_175537148',
 '5_175563657_175907334',
 '5_175923647_177416642',
 '5_177429941_178551058',
 '5_178560621_179290850',
 '5_179309126_179400068',
 '5_179411268_180184269',
 '5_180342860_180362342',
 '5_180379352_180644810',
 '6_5839_85465',
 '6_92884_125392',
 '6_126550_142586',
 '6_146738_154410',
 '6_204528_238441',
 '6_252939_284743',
 '6_295212_314420',
 '6_315257_320890',
 '6_334423_600935',
 '6_611289_618999',
 '6_623776_634345',
 '6_655129_1291357',
 '6_1292057_1353261',
 '6_1358498_1359129',
 '6_1361599_1435871',
 '6_1436117_1512043',
 '6_1535319_2846224',
 '6_2851182_4639919',
 '6_4651403_4923955',
 '6_4933188_6340443',
 '6_6356121_7863271',
 '6_7879466_9392103',
 '6_9450338_11338185',
 '6_11346965_12462252',
 '6_12512986_14535258',
 '6_14553443_16323782',
 '6_16343597_18497312',
 '6_18502918_18536678',
 '6_18550170_19001738',
 '6_19049822_20716660',
 '6_20726739_22048197',
 '6_22060377_24236375',
 '6_24244934_26055528',
 '6_26071233_26265245',
 '6_26270597_27455236',
 '6_27464061_28756233',
 '6_28803010_29931073',
 '6_29939288_29950805',
 '6_29962849_30010234',
 '6_30021894_30031367',
 '6_30040917_30081128',
 '6_30100446_31385778',
 '6_31395330_31558079',
 '6_31564655_32119501',
 '6_32123032_32519935',
 '6_32586131_32600962',
 '6_32605300_32629848',
 '6_32634044_32660090',
 '6_32672983_32702995',
 '6_32718991_32728487',
 '6_32732764_32738443',
 '6_32766023_32821094',
 '6_32831879_35335888',
 '6_35344147_37360148',
 '6_37375174_39260751',
 '6_39271467_39767959',
 '6_39777677_40701218',
 '6_40747924_42826227',
 '6_42836838_44732805',
 '6_44758471_45096253',
 '6_45107837_47047807',
 '6_47058985_49231488',
 '6_49256992_50627364',
 '6_50659323_50928750',
 '6_50933781_52204787',
 '6_52211708_53295979',
 '6_53306500_55847962',
 '6_55859081_57298746',
 '6_57313842_57468298',
 '6_57477427_57636798',
 '6_57648021_58019711',
 '6_58122432_58656267',
 '6_58721961_58788688',
 '6_62077839_62654445',
 '6_62663640_63048821',
 '6_63057692_64614816',
 '6_64633346_64705894',
 '6_64750730_65951879',
 '6_65983562_66231264',
 '6_66247043_66553014',
 '6_66559986_66839246',
 '6_66872400_66895777',
 '6_66949287_67633130',
 '6_67665685_68602261',
 '6_68631929_69110566',
 '6_69133049_69809498',
 '6_69820589_70731852',
 '6_70738275_72163725',
 '6_72170740_73920835',
 '6_73930795_74768342',
 '6_74827202_75616671',
 '6_75632175_75961320',
 '6_75968174_77079694',
 '6_77126953_77532707',
 '6_77558013_78882312',
 '6_78930885_78983276',
 '6_79035891_79079988',
 '6_79101978_79133892',
 '6_79161515_80141390',
 '6_80170446_80661257',
 '6_80681800_81065819',
 '6_81088018_85574506',
 '6_85623360_89090699',
 '6_89106148_90015649',
 '6_90034143_91964331',
 '6_92035339_94502615',

In [61]:
result = result.drop(columns="Sample")

In [74]:
from sklearn.feature_selection import SelectKBest
k_best = SelectKBest(k=10)
k_best.fit(result, result['Subgroup'])
scores = k_best.scores_

/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: UserWarning: Features [2834] are constant.
  UserWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:115: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw

In [75]:
scores

array([0.13326444, 0.29393939, 0.52163142, ..., 0.2870674 , 0.18086845,
              inf])

In [86]:
pairs = zip(features_list[1:], scores)

In [90]:
k_best_features = pd.DataFrame(list(pairs), columns=['feature', 'score'])

In [94]:
k_best_features = k_best_features.sort_values('score', ascending=False)

In [96]:
k_best_features[:20]

                    feature       score
2184   17_35286565_35336158  199.029942
2213   17_41458670_41494331   15.348406
1678   12_85986743_87258350   14.615521
2214   17_41527705_41566540   13.706823
1656   12_66035532_66948440   13.180412
1664   12_71710336_71905426   12.971784
854   6_135520431_136095714   12.794493
1677   12_85450052_85962613   12.781829
1667   12_73217711_73482351   12.656842
2210   17_40859120_40926154   12.433844
1679   12_87329145_88538415   12.393002
1674   12_82881635_83804633   12.207224
1663   12_70574871_71644041   12.106180
673     5_70716278_70721505   12.092109
1662   12_70462057_70560603   11.634771
1668   12_73523915_74655845   11.629889
2223   17_43100477_43148025   11.493036
2206   17_38077519_38710043   11.379391
2207   17_38784700_39114890   11.379391
1672   12_75706042_77012738   11.352113